-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Primary.AK47
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Primary:FindFirstChild("Pump Shotgun")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc.Cuffs
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = game:GetService("Players").LocalPlayer.Character,
    [2] = game:GetService("ReplicatedStorage").Assets.Loadout.Misc:FindFirstChild("Frag Grenade")
}

game:GetService("ReplicatedStorage").AddTool:FireServer(unpack(args))


